# Generated by Django 2.2.12 on 2020-04-07 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sstage', models.CharField(choices=[('FG', 'first grade'), ('SG', 'second grade'), ('TG', 'third grade')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=50, verbose_name='Student Name')),
                ('sage', models.IntegerField(null=True, verbose_name='Student Age')),
            ],
        ),
    ]
