# Generated by Django 2.2.12 on 2020-04-08 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Stage', to='hey.Stage'),
        ),
    ]
