# Generated by Django 2.2.12 on 2020-04-12 05:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hey', '0002_student_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default=django.utils.timezone.now, max_length=128, verbose_name='Student Password'),
            preserve_default=False,
        ),
    ]
